version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3-selectable-cli"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9q5natp5ivgk"
s3_prefix = "s3-selectable-cli"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
